name: Update Coffee Price
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

permissions:
  contents: write # QUAN TRỌNG: Cấp quyền ghi cho action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Nâng cấp lên v4
      - name: Set up Python
        uses: actions/setup-python@v5 # Nâng cấp lên v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run script
        run: python get_price.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Update coffee price" || exit 0 # Thêm || exit 0 để tránh lỗi nếu không có thay đổi
          git push
